version: '2'

services:
  elasticsearch_1:
    extends: 
      service: elasticsearch
      file: base.yml
    volumes:
      - es_vol1:/usr/share/elasticsearch/data
    environment:
      - node.name=alpha  

  elasitcsearch_2:
    extends:
      service: elasticsearch
      file: base.yml
    volumes:
      - es_vol2:/usr/share/elasticsearch/data
    environment:
      - node.name=bravo

  elasticsearch_3:
    extends:
      service: elasticsearch
      file: base.yml
    volumes:
      - es_vol3:/usr/share/elasticsearch/data
    environment:
      - node.name=charlie 

  elasticsearch_kibana:
    extends:
      service: elasticsearch
      file: base.yml
    environment:
      - node.data=false
      - node.ingest=false
      - node.master=false
      - search.remote.connect=false
      - node.name=delta
    volumes:
      - es_vol4:/usr/share/elasticsearch/data
   
  kibana:
    extends:
      service: kibana
      file: base.yml
    depends_on:
      - elasticsearch_kibana
    links:
      - elasticsearch_kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch_kibana:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true 
        
volumes:
 es_vol1:
 es_vol2:
 es_vol3:
 es_vol4:
