---

version: '2'
services:
  journalbeat:
    image: eu.gcr.io/avatao-public/journalbeat:el7
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /var/log/journal:/var/log/journal
      - /run/log/journal:/run/log/journal
      - ./journalbeat.yml:/etc/journalbeat/journalbeat.yml
      #- /var/run/systemd/journal/socket:/var/run/systemd/journal/socket:z
    environment:
      - LOGSTASH_HOST=logstash:5044
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.1
    user: root
    volumes:
      #- ./logstash-conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash-pipeline/:/usr/share/logstash/pipeline/
      - ls-local-log:/mnt/logstash
    depends_on:
      - journalbeat
    links:
      - journalbeat
    restart: always
    environment:
      - XPACK_MONITORING_ENABLED=true
      - CONFIG_RELOAD_AUTOMATIC=true
      - QUEUE_TYPE=persisted
      - QUEUE_MAX_BYTES=1024mb
      - QUEUE_CHECKPOINT_ACKS=1024
      - QUEUE_CHECKPOINT_WRITES=1024
      - QUEUE_CHECKPOINT_INTERVAL=10000
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=changeme
      - LOG_LEVEL=error
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    cap_add:
      - IPC_LOCK
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    expose:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
    restart: on-failure:5

  es_curator_cron_delete:
    image: eldersoss/curator-docker
    command: "--http_auth elastic:changeme --host elasticsearch --port 9200 delete indices --older-than 10 --timestring '%Y.%m.%d' --time-unit days"
    links:
        - elasticsearch
    restart: always

 
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true

volumes:
  esdata:
  ls-local-log:
