---

version: '2'
services:
  kafka-zookeeper:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - AUTO_CREATE_TOPICS=true
      - ADVERTISED_PORT=9092

  journalbeat:
    image: eu.gcr.io/avatao-public/journalbeat:el7
    depends_on:
      - kafka-zookeeper
    links:
      - kafka-zookeeper
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /var/log/journal:/var/log/journal
      - /run/log/journal:/run/log/journal
      - ./journalbeat.yml:/etc/journalbeat/journalbeat.yml
      #- /var/run/systemd/journal/socket:/var/run/systemd/journal/socket:z
    environment:
      - KAFKA_HOST=kafka-zookeeper:9092
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.1
    volumes:
      - ./logstash-conf/:/usr/share/logstash/config
      - ./logstash-pipeline/:/usr/share/logstash/pipeline/
      - ls-local-log:/mnt/logstash
    depends_on:
      - journalbeat
    links:
      - journalbeat
    restart: always
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    cap_add:
      - IPC_LOCK
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    expose:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
    restart: on-failure:5

  es_curator_cron_delete:
    image: eldersoss/curator-docker
    command: "--http_auth elastic:changeme --host elasticsearch --port 9200 delete indices --older-than 10 --timestring '%Y.%m.%d' --time-unit days"
    links:
        - elasticsearch
    restart: always

 
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true

volumes:
  esdata:
  ls-local-log:
